---

- name: remove stuff
  become: yes
  shell: |
    rm /etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list && rm /etc/apt/sources.list.d/docker.list
  ignore_errors: yes


- name: Installing docker
  shell: |
    curl -sSL get.docker.com | sh

- name: Adding user {{ ansible_user }} to docker group
  become: yes
  user: name=user
        groups=docker
        append=yes

- name: Edit the daemon.json file (this file most likely won’t exist yet)
  become: yes
  copy:
    src: templates/daemon.json
    dest: /etc/docker/daemon.json

- name: uncomment net.ipv4.ip_forward=1 in /etc/sysctl.conf
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    line: net.ipv4.ip_forward=1




