---
################ Sudo stuff ###############
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: Add sudoers users to wheel group
  user:
    name="{{ ansible_user }}"
    groups=wheel
    state=present

###########################################################

####################### SSH hardening #####################
#making sure ssh key exists on host
- name: Deploy SSH Key
  authorized_key: user=user
                 key="{{ lookup('file', '.ssh/cluster.key.pub') }}"
                 state=present

- name: Disable SSH root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PermitRootLogin'
    line: 'PermitRootLogin no'

- name: Disable SSH password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication yes'
    line: 'PasswordAuthentication no'

###########################################################

- name: Disabling root login completely
  lineinfile:
    path: /etc/passwd
    regexp: "root:x:0:0:root:/root:/bin/bash"
    line: "root:x:0:0:root:/root:/sbin/nologin"

#Disabling cloud init for it has done its work
- name: Ubuntu specific tasks
  block:
  - name: Remove cloud-config to avoid boot delay
    apt:
      name: cloud-init, cloud-config
      state: absent

#remove ubuntu user
- name: Remove Users
  user:
    name: ubuntu
    state: absent
    remove: yes
  when: ansible_distribution == 'Ubuntu'

#yeet snap
- name: remove snap stuff
  import_tasks: remove_snap.yml

- name: Update and upgrade apt packages
  shell:
    cmd: apt update && apt upgrade -y

#Install needed packages
- name: Install needed packages
  package:
    name: "{{ packages }}"
    state: present

######Automatic Upgrades#######################
- name: Copy unattended-upgrades configuration files in place.
  template:
    src: "templates/unattended-upgrades/{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10periodic
    - 50unattended-upgrades

- name: Ensure unattended upgrades is running
  service:
    name: unattended-upgrades
    state: started
    enabled: yes
################################################
#Didnt set hostname with FAI on old pc
- name: Set a hostname
  ansible.builtin.hostname:
    name: old-pc
  when: inventory_hostname in groups['oldpcs']



