---
#requires the server to already have a user set up with passwordless sudo etc. Did that with cloud init. Connected to the server via WLAN and my phones hotspot
- hosts: routers
  gather_facts: no
  become: yes
  vars_files:
    - group_vars/vault.yml
    - group_vars/main.yml

  tasks:
    - name: SSH juggle
      import_tasks: tasks/ssh-juggle.yml
    - name: Gathering facts
      setup:

    - name: Initial Setup
      import_tasks: tasks/initial_setup.yml

    - name: Install extra packages for router
      package:
        name: "{{ extra_packages_router }}"
        state: present

    - name: Setting up interfaces
      import_tasks: tasks/router/setting_up_interfaces.yml

    - name: Setting up DNS server and DHCP
      import_tasks: tasks/router/DNS_DHCP.yml

    - name: Setting up firewall and routing
      import_tasks: tasks/router/routing_firewall.yml

    - name: Setting up fail2ban and getting it to work with firehol
      import_tasks: tasks/router/fail2ban_with_firehol.yml

############# Set up cluster control ############
    - name: Copy power script to router
      copy:
        src: templates/python_scripts/power.py
        dest: /home/user/power.py

##################################################
    - name: Disabling HDMI
      cron:
        name: "Disabling HDMI port"
        special_time: reboot
        job: "sleep 120s && /opt/vc/bin/tvservice -o"

    - name: Disabling Raspberry Pis LEDS
      copy:
        src: templates/boot_config/config.txt
        dest: /boot/firmware/config.txt

    - name: Reboot
      reboot:

    - name: Disabling Wlan #will of course cut off connection if connected via WLAN
      command: ifconfig wlan0 down






