---
#requires the server to already have a user set up. I used cloudinit on the raspberry pis and FAI (https://fai-project.org/) for an automatic installation on the old pc.
- hosts: old-pcs, pimasters, piworkers
  gather_facts: no #facts will be gathered later after ssh juggle
  become: yes
  vars_files:
    - group_vars/vault.yml
    - group_vars/main.yml

  tasks:
    - name: SSH juggle
      import_tasks: tasks/ssh-juggle.yml
    - name: Gathering facts
      setup:
    - name: Initial Setup
      import_tasks: tasks/initial_setup.yml

    - name: Reboot host and wait for it to restart
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami

    - name: disabling Wlan
      become: yes
      ansible.builtin.command: ifconfig wlan0 down

